/*
 MIT
 @fileOverview Favico animations
 @author Miroslav Magda, http://blog.ejci.net
 @version 0.3.2
*/
(function(){var s=function(w){var x,s,u,A;function B(a){if(a.paused||a.ended||t)return!1;try{b.clearRect(0,0,d,e),b.drawImage(a,0,0,d,e)}catch(l){}setTimeout(B,g.duration,a);v.setIcon(m)}function E(a){a=a.replace(/^#?([a-f\d])([a-f\d])([a-f\d])$/i,function(a,b,c,d){return b+b+c+c+d+d});return(a=/^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(a))?{r:parseInt(a[1],16),g:parseInt(a[2],16),b:parseInt(a[3],16)}:!1}function F(a,b){var c={},f;for(f in a)c[f]=a[f];for(f in b)c[f]=b[f];return c}w=w?w:{};
var C={bgColor:"#d00",textColor:"#fff",fontFamily:"sans-serif",fontStyle:"bold",type:"circle",position:"down",animation:"slide",elementId:!1},c,k,e,d,m,b,h,r,y,D,n,t;A=u=s=x=void 0;x=/firefox/i.test(navigator.userAgent.toLowerCase());s=/chrome/i.test(navigator.userAgent.toLowerCase());u=/opera/i.test(navigator.userAgent.toLowerCase());/msie/i.test(navigator.userAgent.toLowerCase())||/trident/i.test(navigator.userAgent.toLowerCase());A=s||x||u;var p=[];n=function(){};r=t=!1;var q={ready:function(){r=
!0;q.reset();n()},reset:function(){p=[];y=!1;b.clearRect(0,0,d,e);b.drawImage(h,0,0,d,e);v.setIcon(m)},start:function(){if(r&&!D){var a=function(){y=p[0];D=!1;0<p.length&&(p.shift(),q.start())};0<p.length&&(D=!0,y?g.run(y.options,function(){g.run(p[0].options,function(){a()},!1)},!0):g.run(p[0].options,function(){a()},!1))}}},z={},G=function(a){a.n=Math.abs(a.n);a.x*=d;a.y*=e;a.w*=d;a.h*=e;return a};z.circle=function(a){a=G(a);var l=!1;9<a.n&&100>a.n?(a.x-=0.4*a.w,a.w*=1.4,l=!0):100<=a.n&&(a.x-=0.65*
a.w,a.w*=1.65,l=!0);b.clearRect(0,0,d,e);b.drawImage(h,0,0,d,e);b.beginPath();b.font=c.fontStyle+" "+Math.floor(a.h*(99<a.n?0.85:1))+"px "+c.fontFamily;b.textAlign="center";l?(b.moveTo(a.x+a.w/2,a.y),b.lineTo(a.x+a.w-a.h/2,a.y),b.quadraticCurveTo(a.x+a.w,a.y,a.x+a.w,a.y+a.h/2),b.lineTo(a.x+a.w,a.y+a.h-a.h/2),b.quadraticCurveTo(a.x+a.w,a.y+a.h,a.x+a.w-a.h/2,a.y+a.h),b.lineTo(a.x+a.h/2,a.y+a.h),b.quadraticCurveTo(a.x,a.y+a.h,a.x,a.y+a.h-a.h/2),b.lineTo(a.x,a.y+a.h/2),b.quadraticCurveTo(a.x,a.y,a.x+
a.h/2,a.y)):b.arc(a.x+a.w/2,a.y+a.h/2,a.h/2,0,2*Math.PI);b.fillStyle="rgba("+c.bgColor.r+","+c.bgColor.g+","+c.bgColor.b+","+a.o+")";b.fill();b.closePath();b.beginPath();b.stroke();b.fillStyle="rgba("+c.textColor.r+","+c.textColor.g+","+c.textColor.b+","+a.o+")";999<a.n?b.fillText((9999<a.n?9:Math.floor(a.n/1E3))+"k+",Math.floor(a.x+a.w/2),Math.floor(a.y+a.h-0.2*a.h)):b.fillText(a.n,Math.floor(a.x+a.w/2),Math.floor(a.y+a.h-0.15*a.h));b.closePath()};z.rectangle=function(a){a=G(a);9<a.n&&100>a.n?(a.x-=
0.4*a.w,a.w*=1.4):100<=a.n&&(a.x-=0.65*a.w,a.w*=1.65);b.clearRect(0,0,d,e);b.drawImage(h,0,0,d,e);b.beginPath();b.font="bold "+Math.floor(a.h*(99<a.n?0.9:1))+"px sans-serif";b.textAlign="center";b.fillStyle="rgba("+c.bgColor.r+","+c.bgColor.g+","+c.bgColor.b+","+a.o+")";b.fillRect(a.x,a.y,a.w,a.h);b.fillStyle="rgba("+c.textColor.r+","+c.textColor.g+","+c.textColor.b+","+a.o+")";999<a.n?b.fillText((9999<a.n?9:Math.floor(a.n/1E3))+"k+",Math.floor(a.x+a.w/2),Math.floor(a.y+a.h-0.2*a.h)):b.fillText(a.n,
Math.floor(a.x+a.w/2),Math.floor(a.y+a.h-0.15*a.h));b.closePath()};var v={getIcon:function(){var a=!1;if(c.elementId)a=document.getElementById(c.elementId),a.setAttribute("href",a.getAttribute("src"));else{a:{for(var a=document.getElementsByTagName("head")[0].getElementsByTagName("link"),b=a.length-1;0<=b;b--)if(/icon/i.test(a[b].getAttribute("rel"))){a=a[b];break a}a=!1}!1===a&&(a=document.createElement("link"),a.setAttribute("rel","icon"),document.getElementsByTagName("head")[0].appendChild(a))}a.setAttribute("type",
"image/png");return a},setIcon:function(a){a=a.toDataURL("image/png");if(c.elementId)document.getElementById(c.elementId).setAttribute("src",a);else if(x||u){var b=k;k=document.createElement("link");u&&k.setAttribute("rel","icon");k.setAttribute("rel","icon");k.setAttribute("type","image/png");document.getElementsByTagName("head")[0].appendChild(k);k.setAttribute("href",a);b.parentNode&&b.parentNode.removeChild(b)}else k.setAttribute("href",a)}},g={duration:40,types:{}};g.types.fade=[{x:0.4,y:0.4,
w:0.6,h:0.6,o:0},{x:0.4,y:0.4,w:0.6,h:0.6,o:0.1},{x:0.4,y:0.4,w:0.6,h:0.6,o:0.2},{x:0.4,y:0.4,w:0.6,h:0.6,o:0.3},{x:0.4,y:0.4,w:0.6,h:0.6,o:0.4},{x:0.4,y:0.4,w:0.6,h:0.6,o:0.5},{x:0.4,y:0.4,w:0.6,h:0.6,o:0.6},{x:0.4,y:0.4,w:0.6,h:0.6,o:0.7},{x:0.4,y:0.4,w:0.6,h:0.6,o:0.8},{x:0.4,y:0.4,w:0.6,h:0.6,o:0.9},{x:0.4,y:0.4,w:0.6,h:0.6,o:1}];g.types.none=[{x:0.4,y:0.4,w:0.6,h:0.6,o:1}];g.types.pop=[{x:1,y:1,w:0,h:0,o:1},{x:0.9,y:0.9,w:0.1,h:0.1,o:1},{x:0.8,y:0.8,w:0.2,h:0.2,o:1},{x:0.7,y:0.7,w:0.3,h:0.3,
o:1},{x:0.6,y:0.6,w:0.4,h:0.4,o:1},{x:0.5,y:0.5,w:0.5,h:0.5,o:1},{x:0.4,y:0.4,w:0.6,h:0.6,o:1}];g.types.popFade=[{x:0.75,y:0.75,w:0,h:0,o:0},{x:0.65,y:0.65,w:0.1,h:0.1,o:0.2},{x:0.6,y:0.6,w:0.2,h:0.2,o:0.4},{x:0.55,y:0.55,w:0.3,h:0.3,o:0.6},{x:0.5,y:0.5,w:0.4,h:0.4,o:0.8},{x:0.45,y:0.45,w:0.5,h:0.5,o:0.9},{x:0.4,y:0.4,w:0.6,h:0.6,o:1}];g.types.slide=[{x:0.4,y:1,w:0.6,h:0.6,o:1},{x:0.4,y:0.9,w:0.6,h:0.6,o:1},{x:0.4,y:0.9,w:0.6,h:0.6,o:1},{x:0.4,y:0.8,w:0.6,h:0.6,o:1},{x:0.4,y:0.7,w:0.6,h:0.6,o:1},
{x:0.4,y:0.6,w:0.6,h:0.6,o:1},{x:0.4,y:0.5,w:0.6,h:0.6,o:1},{x:0.4,y:0.4,w:0.6,h:0.6,o:1}];g.run=function(a,b,d,f){var e=g.types[document.hidden||document.msHidden||document.webkitHidden||document.mozHidden?"none":c.animation];f=!0===d?"undefined"!==typeof f?f:e.length-1:"undefined"!==typeof f?f:0;b=b?b:function(){};f<e.length&&0<=f?(z[c.type](F(a,e[f])),setTimeout(function(){f=d?f-1:f+1;g.run(a,b,d,f)},g.duration),v.setIcon(m)):b()};(function(){c=F(C,w);c.bgColor=E(c.bgColor);c.textColor=E(c.textColor);
c.position=c.position.toLowerCase();c.animation=g.types[""+c.animation]?c.animation:C.animation;if("up"===c.position)for(var a=0;a<g.types[""+c.animation].length;a++){var l=g.types[""+c.animation][a];l.y=0.6>l.y?l.y-0.4:l.y-2*l.y+(1-l.w);g.types[""+c.animation][a]=l}c.type=z[""+c.type]?c.type:C.type;try{k=v.getIcon(),m=document.createElement("canvas"),h=document.createElement("img"),k.hasAttribute("href")?(h.setAttribute("src",k.getAttribute("href")),h.onload=function(){e=0<h.height?h.height:32;d=
0<h.width?h.width:32;m.height=e;m.width=d;b=m.getContext("2d");q.ready()}):(h.setAttribute("src",""),d=e=32,h.height=e,h.width=d,m.height=e,m.width=d,b=m.getContext("2d"),q.ready())}catch(H){throw"Error initializing favico. Message: "+H.message;}})();return{badge:function(a,b){n=function(){try{if(0<a){g.types[""+b]&&(c.animation=b);p.push({type:"badge",options:{n:a}});if(100<p.length)throw"Too many badges requests in queue.";q.start()}else q.reset()}catch(d){throw"Error setting badge. Message: "+
d.message;}};r&&n()},video:function(a){n=function(){try{"stop"===a?(t=!0,q.reset(),t=!1):a.addEventListener("play",function(){B(this)},!1)}catch(b){throw"Error setting video. Message: "+b.message;}};r&&n()},image:function(a){n=function(){try{var c=a.width,g=a.height,f=document.createElement("img"),h=c/d<g/e?c/d:g/e;f.setAttribute("src",a.getAttribute("src"));f.height=g/h;f.width=c/h;b.clearRect(0,0,d,e);b.drawImage(f,0,0,d,e);v.setIcon(m)}catch(k){throw"Error setting image. Message: "+k.message;}};
r&&n()},webcam:function(a){window.URL&&window.URL.createObjectURL||(window.URL=window.URL||{},window.URL.createObjectURL=function(a){return a});if(A){var b=!1;navigator.getUserMedia=navigator.getUserMedia||navigator.oGetUserMedia||navigator.msGetUserMedia||navigator.mozGetUserMedia||navigator.webkitGetUserMedia;n=function(){try{"stop"===a?(t=!0,q.reset(),t=!1):(b=document.createElement("video"),b.width=d,b.height=e,navigator.getUserMedia({video:!0,audio:!1},function(a){b.src=URL.createObjectURL(a);
b.play();B(b)},function(){}))}catch(c){throw"Error setting webcam. Message: "+c.message;}};r&&n()}},reset:q.reset}};"undefined"!==typeof define&&define.amd?define([],function(){return s}):"undefined"!==typeof module&&module.exports?module.exports=s:this.Favico=s})();